### ISSUE TITLE
Retroarch/RetroPie Super Mario Allstars

### ISSUE THREAD

**Issue by nemo1966** [libretro/snes9x2005#15]
Hi the gamepads don't seem to work on the game. The gamepads work on the eulation station menus and the in game menus (select player - select cart etc) but sop working when you actually get to the game. (when game actually starts).

Same gamepad works fine in lr-snes9x-next

thanks

**Comment by netux79** [comment]
Did you try enabling the core option to swap pads? I think this is a know issue. I don't have retropie but this fix works with all other platforms.

**Comment by cheatfreak47** [comment]
I can confirm this issue occurs on a lot of ports, this particularly affects the 3DS port, because Snes9x2002 and Snes9x2005 are the only cores light enough on resources to run well on the console, (specifically the n3DS)

**Comment by jamsilva** [comment]
This should be working correctly as of bc74743.

**Comment by meepingsnesroms** [comment]
Post here if its still not working, the original reporter isnt going to test it.
